fix matplotlib cannot import name _cntr
Fix ImportError: cannot import name _cntr 
because from matplotlib version 2.2.0 no longer support matplotlib._cntr() you have to install matplotlib version 2.1.2